document.writeln("<section class=\"form\"> ");
document.writeln("<div class=\"weui-cells \"> ");
document.writeln("  <h3 class=\"pb20\">Request A Quotation</h3> ");
document.writeln("  <div class=\"border-bottom\"></div> ");
document.writeln("</div> ");
document.writeln("  <form action=\"http://inquiry.zenithcrusher.com/updata_ppc.php\" method=\"post\" name=\"form\" id=\"proForm\"> ");
document.writeln("  <div class=\"weui-cells weui-cells_form border-all-solid\" > ");
document.writeln("    <div class=\"weui-cell \"> ");
document.writeln("      <div class=\"weui-cell__bd\"> ");
document.writeln("        <input class=\"weui-input fs14\" type=\"text\" required name=\"name\" type=\"text\" id=\"name\" placeholder=\"You Name:\"> ");
document.writeln("      </div> ");
document.writeln("    </div> ");
document.writeln("  </div> ");
document.writeln("  <div class=\"weui-cells weui-cells_form border-all-solid\"> ");
document.writeln("    <div class=\"weui-cell \"> ");
document.writeln("      <div class=\"weui-cell__bd\"> ");
document.writeln("        <input class=\"weui-input fs14\" type=\"telephone\" placeholder=\"Telephone Number:\" name=\"phone\"  id=\"tel\"> ");
document.writeln("      </div> ");
document.writeln("    </div> ");
document.writeln("  </div> ");
document.writeln("  <div class=\"weui-cells weui-cells_form border-all-solid\"> ");
document.writeln("    <div class=\"weui-cell \"> ");
document.writeln("      <div class=\"weui-cell__bd\"> ");
document.writeln("        <input class=\"weui-input fs14\" type=\"email\" required placeholder=\"Email:\" name=\"email\" id=\"email\"> ");
document.writeln("      </div> ");
document.writeln("    </div> ");
document.writeln("  </div> ");
document.writeln("  <div class=\"weui-cells weui-cells_form border-all-solid\"> ");
document.writeln("    <div class=\"weui-cell \"> ");
document.writeln("      <div class=\"weui-cell__bd\"> ");
document.writeln("        <input class=\"weui-input fs14\" type=\"text\" name=\"company\" placeholder=\"Company Name:\"> ");
document.writeln("      </div> ");
document.writeln("    </div> ");
document.writeln("  </div> ");
document.writeln("  <div class=\"weui-cells weui-cells_form border-all-solid\"> ");
document.writeln("    <div class=\"weui-cell \"> ");
document.writeln("      <div class=\"weui-cell__bd\"> ");
document.writeln("        <input class=\"weui-input fs14\" type=\"text\" name=\"country\" placeholder=\"Location Of Equipment:\"> ");
document.writeln("      </div> ");
document.writeln("    </div> ");
document.writeln("  </div> ");
document.writeln("  <div class=\"weui-cells weui-cells_form border-all-solid\"> ");
document.writeln("    <div class=\"weui-cell \"> ");
document.writeln("      <div class=\"weui-cell__bd\"> ");
document.writeln("        <input class=\"weui-input fs14\" type=\"text\" name=\"application\" placeholder=\"Application:\"> ");
document.writeln("      </div> ");
document.writeln("    </div> ");
document.writeln("  </div> ");
document.writeln("  <div class=\"weui-cells weui-cells_form border-all-solid\"> ");
document.writeln("    <div class=\"weui-cell weui-cell_select\"> ");
document.writeln("      <div class=\"weui-cell__bd\"> ");
document.writeln("        <select class=\"weui-select fs14\" name=\"product\" id=\"product\"> ");
document.writeln("          <option selected=\"\" value=\"0\">Select Product</option> ");
document.writeln("          <optgroup label=\"Crushing Machines\"> ");
document.writeln("            <option value=\"1\">Jaw Crusher</option> ");
document.writeln("            <option value=\"2\">Cone Crusher</option> ");
document.writeln("            <option value=\"3\">Impact Crusher</option> ");
document.writeln("            <option value=\"4\">Sand Making Machine</option> ");
document.writeln("            <option value=\"5\">Vibrating Feeder</option> ");
document.writeln("            <option value=\"6\">Vibrating Screen</option> ");
document.writeln("            <option value=\"7\">Belt Conveyor</option> ");
document.writeln("          </optgroup> ");
document.writeln("          <optgroup label=\"Grinding Mills\"> ");
document.writeln("            <option value=\"8\">0-3mm Powder Mill</option> ");
document.writeln("            <option value=\"9\">100-625mesh Powder Mill</option> ");
document.writeln("            <option value=\"10\">625-2500mesh Powder Mill</option> ");
document.writeln("          </optgroup> ");
document.writeln("          <optgroup label=\"Mobile Plants\"> ");
document.writeln("            <option value=\"11\">Wheel Mobile Crushing plant</option> ");
document.writeln("            <option value=\"12\">Track-type mobile crushing plant</option> ");
document.writeln("          </optgroup> ");
document.writeln("        </select> ");
document.writeln("      </div> ");
document.writeln("    </div> ");
document.writeln("  </div> ");
document.writeln("  <div class=\"weui-cells weui-cells_form border-all-solid\"> ");
document.writeln("    <div class=\"weui-cell weui-cell_select\"> ");
document.writeln("      <div class=\"weui-cell__bd\"> ");
document.writeln("        <select class=\"weui-select fs14\" id=\"material\"> ");
document.writeln("          <option selected=\"\" value=\"0\">Select Material</option> ");
document.writeln("          <option value=\"1\">Limestone</option> ");
document.writeln("          <option value=\"2\">Calcite</option> ");
document.writeln("          <option value=\"3\">Coal Powder</option> ");
document.writeln("          <option value=\"4\">Gypsum</option> ");
document.writeln("          <option value=\"5\">Dolomite</option> ");
document.writeln("          <option value=\"6\">Barite</option> ");
document.writeln("          <option value=\"7\">Marble</option> ");
document.writeln("          <option value=\"8\">Talc</option> ");
document.writeln("          <option value=\"9\">Basalt</option> ");
document.writeln("          <option value=\"10\">Granite</option> ");
document.writeln("          <option value=\"11\">Building Wastes</option> ");
document.writeln("          <option value=\"12\">Pebble</option> ");
document.writeln("          <option value=\"13\">Tuff</option> ");
document.writeln("          <option value=\"14\">Tailing</option> ");
document.writeln("          <option value=\"15\">Feldspar</option> ");
document.writeln("          <option value=\"16\">&gt;&gt;Others</option> ");
document.writeln("        </select> ");
document.writeln("      </div> ");
document.writeln("    </div> ");
document.writeln("  </div> ");
document.writeln("  <div class=\"weui-cells weui-cells_form border-all-solid\"> ");
document.writeln("   <div class=\"weui-cell\"> ");
document.writeln("     <div class=\"weui-cell__bd\"> ");
document.writeln("       <textarea class=\"weui-textarea\" placeholder=\"Message:\" name=\"content\"  rows=\"3\" id=\"formMsg\"></textarea> ");
document.writeln("       <div class=\"weui-textarea-counter\"><span>0</span>/200</div> ");
document.writeln("     </div> ");
document.writeln("   </div> ");
document.writeln(" </div> ");
document.writeln(" <div class=\"weui-btn-area \"> ");
document.writeln("	<input class=\"weui-btn bgc-e34218\" type=\"Submit\" value=\"submit\" /> ");
document.writeln("	</div> ");
document.writeln("</form> ");
document.writeln("</section> ");